# Generated by Django 5.2 on 2025-08-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=200)),
                ('tipo_archivo', models.CharField(choices=[('Curriculum', 'Curriculum'), ('Vida Laboral', 'Vida Laboral'), ('Otro', 'Otro')], default='Curriculum', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
