# Generated by Django 5.2 on 2025-08-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
