# Generated by Django 5.2 on 2025-12-18 18:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0003_delete_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
